name: MLflow MLproject Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  mlflow_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.2'  # Gunakan versi stabil yang didukung MLflow

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow
        pip install -r requirements.txt

    - name: Run MLflow MLproject
      run: |
        cd MLproject
        mlflow run . --env-manager=local

    - name: Upload artifacts (optional)
      uses: actions/upload-artifact@v4
      with:
        name: mlruns
        path: MLproject/mlruns

    - name: Save mlruns to repo
      if: success()
      run: |
        git config --global user.name yogaWidodo
        git config --global user.email chaintroopers88@gmail.com
        git fetch origin main
        git checkout main
        git add MLproject/mlruns/
        git commit -m "Save mlruns from CI run [skip ci]" || echo "Nothing to commit"
        git push originn main